sudo: false
language: python
python:
    - '2.7'
    - '3.5'
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
      install: tox
      script: tox
    - python: 3.6
      env: TOXENV=py36
      install: tox
      script: tox
    - python: 3.5
      env: CODESTYLE=true
install:
    - 'pip install -r requirements.txt'
    - 'pip install -r requirements.test.txt'
script:
    - 'py.test --cov=pycco tests/'
    - 'python -m pycco.main pycco/main.py'
after_success:
    - coveralls
